### PR TITLE
docs: translation & miscellaneous enhancement

### PR DESCRIPTION
**Pull request by KnowsCount**
markdown formatting, docs translation and readme enhancement.

### CODE REVIEW

**Comment by ShenQingchuan** [comment]
Some of these changes do make sense.

But I didn't see any necessity in this PR for the "Tab indent": from 2 spaces to 4 spaces,

**Comment by KnowsCount** [comment]
ahh I can change these back... it's my vs code. I thought it might help so I left it that way.

**Comment by ShenQingchuan** [comment]
It must be more complicated for you to turn those settings around and debug, I would like to pick some of your changes for docs and submit a new commit, and I may close this PR.

Thanks for your effort.

**Comment by KnowsCount** [comment]
of course. should I close this or should you?

**Pull request closed without merging**
